# TERMINUS CONSTANTS
#
# These are default values for each of the constants bearing the same name
# within Terminus. They may be overridden by exporting an environmental
# variable of the same name, or by adding it to a file named ".env" in the
# directory from which you are running Terminus.
---

# App
TERMINUS_VERSION: '2.4.1'

# Connectivity
TERMINUS_HOST:      'terminus.pantheon.io'
TERMINUS_HOST_CERT: null
TERMINUS_PORT:      443
TERMINUS_PROTOCOL:  'https'
TERMINUS_SSH_HOST:  null

# Settings
TERMINUS_TIMEOUT: 86400

# User Prompts
TERMINUS_DASHBOARD_HOST:     'dashboard.pantheon.io'
TERMINUS_DASHBOARD_PROTOCOL: 'https'

# Localization
TERMINUS_DATE_FORMAT:     'Y-m-d H:i:s'
TERMINUS_MONETARY_FORMAT: '$%01.2f'
TERMINUS_TIME_ZONE:       'UTC'

# File Storage
TERMINUS_CACHE_DIR:         '[[ TERMINUS_USER_HOME ]]/.terminus/cache'
TERMINUS_PLUGINS_DIR:       '[[ TERMINUS_USER_HOME ]]/.terminus/plugins'
TERMINUS_COMMAND_CACHE_DIR: '[[ TERMINUS_CACHE_DIR ]]/commands'
TERMINUS_TOKENS_DIR:        '[[ TERMINUS_CACHE_DIR ]]/tokens'
TERMINUS_ASSETS_DIR:        '[[ TERMINUS_ROOT ]]/assets'

# Helpers
TERMINUS_USER: null
TERMINUS_SITE: null
TERMINUS_ENV:  null
TERMINUS_ORG:  null

# Region
TERMINUS_COMMAND_SITE_OPTIONS_REGION: null

# Testing
TERMINUS_TEST_MODE:    false
TERMINUS_VCR_CASSETTE: null
TERMINUS_VCR_MODE:     null

# Set by Terminus - DO NOT USE
# Terminus
# TERMINUS_PHP
# TERMINUS_ROOT
# TERMINUS_SCRIPT
